package com.bw.weidushop.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.weidushop.bean.AddCarData;
import com.bw.weidushop.bean.User;

import com.bw.weidushop.dao.AddCarDataDao;
import com.bw.weidushop.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addCarDataDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AddCarDataDao addCarDataDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addCarDataDaoConfig = daoConfigMap.get(AddCarDataDao.class).clone();
        addCarDataDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        addCarDataDao = new AddCarDataDao(addCarDataDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(AddCarData.class, addCarDataDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        addCarDataDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AddCarDataDao getAddCarDataDao() {
        return addCarDataDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
