package com.bw.weidushop.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bw.weidushop.bean.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserId = new Property(0, long.class, "userId", true, "_id");
        public final static Property Sex = new Property(1, int.class, "sex", false, "SEX");
        public final static Property SessionId = new Property(2, String.class, "sessionId", false, "SESSION_ID");
        public final static Property NickName = new Property(3, String.class, "nickName", false, "NICK_NAME");
        public final static Property String = new Property(4, String.class, "string", false, "STRING");
        public final static Property HeadPic = new Property(5, String.class, "headPic", false, "HEAD_PIC");
        public final static Property IsLogin = new Property(6, int.class, "isLogin", false, "IS_LOGIN");
        public final static Property Password = new Property(7, String.class, "password", false, "PASSWORD");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: userId
                "\"SEX\" INTEGER NOT NULL ," + // 1: sex
                "\"SESSION_ID\" TEXT," + // 2: sessionId
                "\"NICK_NAME\" TEXT," + // 3: nickName
                "\"STRING\" TEXT," + // 4: string
                "\"HEAD_PIC\" TEXT," + // 5: headPic
                "\"IS_LOGIN\" INTEGER NOT NULL ," + // 6: isLogin
                "\"PASSWORD\" TEXT);"); // 7: password
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getUserId());
        stmt.bindLong(2, entity.getSex());
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(3, sessionId);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(4, nickName);
        }
 
        String string = entity.getString();
        if (string != null) {
            stmt.bindString(5, string);
        }
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(6, headPic);
        }
        stmt.bindLong(7, entity.getIsLogin());
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(8, password);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getUserId());
        stmt.bindLong(2, entity.getSex());
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(3, sessionId);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(4, nickName);
        }
 
        String string = entity.getString();
        if (string != null) {
            stmt.bindString(5, string);
        }
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(6, headPic);
        }
        stmt.bindLong(7, entity.getIsLogin());
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(8, password);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.getLong(offset + 0), // userId
            cursor.getInt(offset + 1), // sex
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sessionId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // nickName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // string
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // headPic
            cursor.getInt(offset + 6), // isLogin
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // password
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setUserId(cursor.getLong(offset + 0));
        entity.setSex(cursor.getInt(offset + 1));
        entity.setSessionId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNickName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setString(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHeadPic(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsLogin(cursor.getInt(offset + 6));
        entity.setPassword(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setUserId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getUserId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
